
DROP TABLE IF EXISTS user_review CASCADE;

DROP TABLE IF EXISTS payment CASCADE;

DROP TABLE IF EXISTS cart CASCADE;

DROP TABLE IF EXISTS order_detail CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS product_image CASCADE;

DROP TABLE IF EXISTS product_category_map CASCADE;

DROP TABLE IF EXISTS temperature CASCADE;

DROP TABLE IF EXISTS product_sizes CASCADE;

DROP TABLE IF EXISTS sizes CASCADE;

DROP TABLE IF EXISTS product_variant CASCADE;

DROP TABLE IF EXISTS variants CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS product_category CASCADE;

DROP TABLE IF EXISTS users CASCADE;
