GET http://localhost:3002/admin/users HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/admin/users?page=1&limit=5 HTTP/1.1
content-type: application/json


###
POST http://localhost:3002/auth/register HTTP/1.1
content-type: application/json

{
    "name": "irul",
    "email": "irul2@gmail.com",
    "password": "secret22",
    "confirmPassword": "secret22"
}

###
###
POST http://localhost:3002/auth/login HTTP/1.1
content-type: application/json

{
    "email": "harjasa.satria@gmail.com",
    "password": "password123"
}

###
PUT http://localhost:3002/api/users/1 HTTP/1.1
content-type: application/json

{
    "name": "mahmudnew",
    "email": "mahmud@gmail.com"
}

###
DELETE http://localhost:3002/api/users/9 HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/products HTTP/1.1
content-type: application/json

{
    "name": "silverqueen",
    "desc": "snack cokelat",
    "stock": 100,
    "price": 10000
}

###
GET http://localhost:3002/api/products HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/products?name=macchiato HTTP/1.1
content-type: application/json


###
GET http://localhost:3002/products?page=1&limit=5 HTTP/1.1
content-type: application/json

###
PUT http://localhost:3002/products/17 HTTP/1.1
content-type: application/json

{
    "stock": 200
}

###
GET http://localhost:3002/products/16 HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3002/products/16 HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/reviews HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/reviews HTTP/1.1
content-type: application/json

{
    "userId": 2,
    "productId": 9,
    "orderId": 1,
    "message": "good product",
    "rating": 5
}


###
GET http://localhost:3002/products/1/variants HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/products/1/discounts HTTP/1.1
content-type: application/json

### checkout endpoint
POST http://localhost:3002/checkout/create-order HTTP/1.1
content-type: application/json

{
  "customerId": 1,
  "paymentMethod": "transfer_bank",
  "shippingAddress": "Jl. Merdeka No. 123, Jakarta Pusat, 12190"
}

###
POST http://localhost:3002/checkout/validate HTTP/1.1
content-type: application/json

{
  "customerId": 2
}

###
GET http://localhost:3002/checkout/orders/1 HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/checkout/user/1/orders HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/checkout/orders/2/cancel HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/payments/create HTTP/1.1
content-type: application/json

{
  "orderId": 4,
  "userId": 2,
  "amount": 124.62
}

###
POST http://localhost:3002/payments/1/complete HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/payments/2/fail HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/payments/3/cancel HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/payments/3 HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/payments/order/2 HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/payments/2/refund/request HTTP/1.1
content-type: application/json

###
GET http://localhost:3002/payments/user/1/history HTTP/1.1
content-type: application/json

###
POST http://localhost:3002/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "sakura@gmail.com",
    "password": "secret22"
}

###
GET http://localhost:3002/api/products HTTP/1.1
content-type: application/json
